CREATE DATABASE ETC
	GO

USE ETC;


CREATE TABLE Car(
CarID char(8) NOT NULL,
ID char(10) NOT NULL,
PhoneNumber char(10) NOT NULL,
CustomerName char(10) NOT NULL,
CONSTRAINT CarPK PRIMARY KEY(CarID) 
);


CREATE TABLE PaymentRecord(
CarID char(8) NOT NULL,
Balance money NOT NULL,
Arrears money NOT NULL,
PayDate date NOT NULL,
PayTime time NOT NULL,
CONSTRAINT PaymentRecordFK FOREIGN KEY(CarID)
	REFERENCES Car(CarID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
);


CREATE TABLE Check_Point(
ICFirstEnd char(50) NOT NULL,
CONSTRAINT Check_PointPK PRIMARY KEY(ICFirstEnd)
);


CREATE TABLE Mileagefee(
ICFirstEnd char(50) NOT NULL,
ICPrice money NOT NULL,
CONSTRAINT MileagefeeFK FOREIGN KEY(ICFirstEnd)
	REFERENCES Check_Point(ICFirstEnd)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
);


CREATE TABLE PassRecord(
CarID char(8) NOT NULL,
ICFirstEnd char(50) NOT NULL,
Passtime time NOT NULL,
CONSTRAINT PassRecordFK FOREIGN KEY(CarID)
REFERENCES Car(CarID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION,
CONSTRAINT PassRecordFK2 FOREIGN KEY(ICFirstEnd)
	REFERENCES Check_Point(ICFirstEnd)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
);
